# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('creation_date', models.DateField()),
                ('authorised', models.IntegerField()),
                ('email_verify_code', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
