# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_photogallery_resetpassword_videogallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Memorial',
            fields=[
                ('guid', models.AutoField(primary_key=True, serialize=False)),
                ('accessguid', models.IntegerField()),
                ('fname', models.CharField(max_length=50)),
                ('mname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('dob', models.DateField(db_column='DOB')),
                ('dod', models.DateField(db_column='DOD')),
                ('latitude', models.DecimalField(decimal_places=4, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=4, max_digits=10)),
                ('story', models.TextField()),
                ('relatedlink', models.CharField(max_length=100)),
                ('profilephoto', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'memorial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResetPwd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailid', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'resetpwd',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='ResetPassword',
        ),
        migrations.AlterModelOptions(
            name='access',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='documentgallery',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='photogallery',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='videogallery',
            options={'managed': False},
        ),
    ]
